name: CI

on: [push, pull_request]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: make uninstall
      run: sudo make uninstall
